### ISSUE TITLE
Parse+React 0.5.0

### ISSUE THREAD

**Issue by andrewimm** [ParsePlatform/ParseReact#110]
0.5.0 will mainly update Parse+React to work with the latest version of the Parse JS SDK, v1.6.

- [x] Use the newly-public `currentAsync` method for subscriptions
- [x] Expose a way to specify which SDK (`parse` vs `parse/react-native`) to use in StubParse.js
- [x] Use the new method signature for Op requests
- [x] Remove the /lib and /dist directories from the repository

Following its release, 0.5.0 will only be compatible with SDKs using the new >= 1.6 codebase.

**Comment by andrewimm** [comment]
Everything looks good. Following some tests in React Native, I'll release 0.5.0 on npm

**Comment by bobintornado** [comment]
Love this repo and the speed of development, and I think it will be better if such things could be saved into a CHANGELOG.md.

I could do a PR if you don't mind. Does this repo require CLA?
