### ISSUE TITLE
Parse.User.current()

### ISSUE THREAD

**Issue by leoskye** [ParsePlatform/ParseReact#119]
I'm seeing this error when I run my React Native app:

My observe() function:

```
  observe: function() {
    return {
      user: ParseReact.currentUser,
      current: new Parse.Query('Idea')
        .equalTo('User', Parse.User.current())
        .equalTo('State', Config.IDEA_STATES[Config.CURRENT]),
    };
  },
```

![image](https://cloud.githubusercontent.com/assets/1527177/9951673/5155d0a2-5d7e-11e5-9b93-10c1802b9d23.png)

I tried using Parse.User.currentAsync(), but that returns a Promise instead of Parse.Object. How do I filter by current user in my subscription query?

**Comment by ecesena** [comment]
You should use ACL for this use case. When you create Idea(s), set an ACL. Automagically, when you query for Idea(s), only those accessible by the current user will be returned.

Something like this:
```
actionCreateIdea: function(event) {
  var user = Parse.User.current();

  var acl = new Parse.ACL(user);
  var mutation = 
    ParseReact.Mutation.Create('Idea', {
      ...
      user: user,
      ACL: acl
    });

  mutation.dispatch().then(function() {
    // nothing to do
  });
},
```

**Comment by leoskye** [comment]
If I set the ACL to the current user only, wouldn't that restrict all other users from ever seeing this idea? There are cases where I want to get all ideas belonging to this user, but other cases where I'd want to show all ideas not belonging to the current user.

**Comment by ethandt92** [comment]
I have not tested this but try using a higher order component. The component observes currentUser and passes the user as a prop.

```
class UserComponent {
  observe() {
    return {
      user: ParseReact.currentUser
    }
  }
  render() {
    <YourComponent user={this.data.user}/>
  }
}
class YourComponent {
  observe(props, state) {
    var ideas = new Parse.Query('Idea')
    ideas.equalTo('User', props.user)
    return {
      ideas
    }
  }
}
```

**Comment by ecesena** [comment]
@leoskye (sorry for the delay) yes, as you said ACL would restrict your use case.
I think your issue is that `observe` is processed on componentWillMount, so you need to ensure that the user is already known at that time.

**Comment by leoskye** [comment]
Thanks for all the suggestions. I'll give the decorator a try and find a workaround. It just feels like there should be a more straightforward way to do this since it's a pretty common operation.
