### ISSUE TITLE
Callback on Mutation / MutationBatch?

### ISSUE THREAD

**Issue by mbifulco** [ParsePlatform/ParseReact#122]
Is there a correct way to trigger a callback from a mutation or a mutation batch? I've got a profile page in my app in which users are able to update their metadata (email address, etc), and I'd like to disable the submit button on my form just before I send a `MutationBatch.dispatch()`. I had assumed that I could trigger a callback like this:

```js
var batch = new ParseReact.Mutation.Batch();
creator.dispatch({ batch: batch });
creator.dispatch({ batch: batch });
creator.dispatch({ batch: batch });
batch.dispatch(function(){
  //callback code
});
```

But it doesn't appear that works.  Given that Mutations and MutationBatches are asynchronous, is there a  better way to achieve this?

**Comment by andrewimm** [comment]
`.dispatch()` returns a `Parse.Promise`, which is a far better way to handle asynchronous behavior, as it avoids "callback hell."
You can read more about `Parse.Promise` here: http://blog.parse.com/learn/engineering/whats-so-great-about-javascript-promises/

**Comment by mbifulco** [comment]
Got it - so that makes good sense to me, thanks @andrewimm.  I'm definitely catching up on the learning curve here, so pardon me if this is a silly question -- if I try to execute this.setState() within the Parse.Promise success handler, I get the following:

```
Uncaught TypeError: this.setState is not a function
```

At that point, `this` seems to refer to the `Window` object.

**Comment by mbifulco** [comment]
Maybe this isn't something I should be using `state` for, too.  I'll admit to being at least a little cloudy on that.

**Comment by andrewimm** [comment]
In that scenario, `this` likely does not refer to the component. There are three different ways JS programmers typically get around this:
1) Save a reference to `this`
```js
var self = this;
batch.dispatch(function() {
  self.setState({ })
});
```

2) Bind the function ahead of time
```js
var handler = function() {
  this.setState({ })
};
batch.dispatch(handler.bind(this))
```

3) My favorite. If you're using a system like Babel to compile ES6 JS to something more widely supported, you can use the new fat-arrow function syntax:
```js
batch.dispatch(() => {
  // In here, 'this' refers to the same thing it would outside this function
  this.setState({ })
});
```

**Comment by mbifulco** [comment]
I'd come across the first option you shared there a fair few times recently - I was wondering what that was about.  Thanks for the quick tutorial!  I'll give the ES6 method a shot.
