### ISSUE TITLE
Get image from uri for upload

### ISSUE THREAD

**Issue by kevinzzz007** [ParsePlatform/ParseReact#126]
Is there a recommended way to upload images to Parse?  I used https://github.com/marcshilling/react-native-image-picker to pick images, but it only gives me the image uri, but Parse needs a file object, so I am not sure how to proceed next...

**Comment by albertolive** [comment]
var photoToUpload = '';
var photoName = 'picture1.jpg';

photoToUpload = e.target.form.photoUpload.files[0]; // Here find your image. 

var parseFile = new Parse.File(photoName, photoToUpload);

Hope it helps.

**Comment by kevinzzz007** [comment]
@albertolive  thanks so much!  I will try it out and keep you posted :-)
