### ISSUE TITLE
Setting ParseReact.currentUser as pointer of a object

### ISSUE THREAD

**Issue by zimok** [ParsePlatform/ParseReact#13]
It seems that when creating a Mutation, passing the `ParseReact.currentUser` as a pointer doesn't work:

    var obj = ParseReact.Mutation.Create('MyObject', {
        createdBy: ParseReact.currentUser // this is a Pointer field
    }).dispatch()

in this way the object is created and persisted but the `createdBy` field is left empty.
Instead, by using 'classical' Parse JS sdk, it works as usual:

    // object initialization here ...
    // ...
    object.set("createdBy", Parse.User.current())
    object.save()

Is this the expected behaviour?

**Comment by andrewimm** [comment]
`ParseReact.currentUser` is a [subscription object](/docs/api/LocalSubscriptions.md), not a pointer to the current user. If you want to set the current user as a value like this, you need to either subscribe your component to `ParseReact.currentUser` and use that value (take a look at the AnyBudget example app for how to do this), or set the value to `Parse.User.current().toPlainObject()`.

```js
ParseReact.Mutation.Create('MyObject', {
  createdBy: Parse.User.current().toPlainObject()
}).dispatch();
```

For utility's sake, you should be able to drop a Parse Object directly in as a value, and have it automatically converted to a pointer. I'll add this feature later today.

**Comment by andrewimm** [comment]
I've updated to v0.1.4. You should now be able to use the code above without the extra `.toPlainObject()` call.
