### ISSUE TITLE
Can't get React.js app to pull data from Parse using ParseReact and “this.data”

### ISSUE THREAD

**Issue by nickbae91** [ParsePlatform/ParseReact#130]
So I have a simple App made with React.js, React-Webpack, and Material-UI, and currently trying to connect it with Parse.com. I have the connection established (application keys correctly entered), and verified the connection.

However, when I try to pull data from Parse.com, my app crashes... (I get the Webpack's error message "If you can see this message, something is broken or JS is not enabled"). All I added was:
1.the "require"s for Parse and ParseReact
2.the ParseReact.Mixin
3."observe" method from the Mixin for the Query
4."this.data.listItems" (listItems = the object into which I put in the Query

Below is the code for the page where the error is happening.

As for the Parse.com side of things, I've successfully imported a JSON file to create a class named "Focus", with an attribute called "name" that contains the label for that data row.

Thank you so much in advance...!! I'm new to ReactJS & Parse, and this has been an issue I've been struggling with for a couple of days already and attempted to fix this countless times/ways with no luck...

        'use strict';
    
        var React = require('react/addons');
        var Parse = require('parse');
        var ParseReact = require('parse-react');
        //var ExplorerPage = require('./Explorerpage');
    
        var { List, ListItem, Mixins, Styles } = require('material-ui');
        var { Spacing, Colors } = Styles;
        var { StyleResizable, StylePropable } = Mixins;
        
        var ExplorerWithNav = React.createClass({
        mixins: [ParseReact.Mixin, StyleResizable, StylePropable],
    
        //This is the observe method, and I triple-checked the Class' name to be "Focus" and its string-based labeling attribute to be called "name".
        observe() {
           return {
              listItems: (new Parse.Query('Focus')).ascending('name')
           };
        },

        //State object that tracks the selected item name as a string.
        getInitialState() {
          return {selecteditem: ''};
        },

        //muiTheme is used for a styling method that has been omitted from this code.
        contextTypes: {
          muiTheme: React.PropTypes.object
        },

        render() {
        //this.getStyles() is working fine - omitted in this code.
        let styles = this.getStyles();
    
            var listitems = this.data.listItems.map(function(item, i) {
        return (
            <ListItem
              key={i}
              primaryText={item.name}
              style={this.state.selecteditem === item.name ? {color: this.context.muiTheme.component.menuItem.selectedTextColor} : null}
              onTouchTap={this._onListItemClick.bind(null, item.name)} />
              );
            }
          }, this);
    
          return (
            <div style={styles.root}>
              <div style={styles.content}>
                 //ExplorerPage is another component that's supposed to display the information selected by the MenuItem, but excluded to try fix this particular issue first.
                 //<ExplorerPage selected={this.state.selecteditem} />
              </div>
              <div style={styles.secondaryNav}>
                <List subheader="Nested List Items">
                {listitems}
                </List>
              </div>
            </div>
          );
        },
    
        _onListItemClick(name) {
          this.setState({selecteditem: name});
        }
    
        });
    
        module.exports = ExplorerWithNav;

**Comment by yutin1987** [comment]
+1

**Comment by umfana** [comment]
Do you have a stacktrace from the console? Hard to tell from the generic Webpack error where it is crashing. Off the top of my head, maybe check to see whether `this.data.listItems` is defined first before calling `map()` on it.

**Comment by umfana** [comment]
In fact, at second glance, I notice you're mixing ES5 and ES6 concepts in your component - using `React.createClass` and `mixins` but also ES6 function definitions like `observe() { ... }`. Perhaps try it using the old `observe: function() { ... }`.

**Comment by nickbae91** [comment]
Hey,

So I've just figured it out yesterday and it's something ridiculous. I tried opening index.html via Chrome instead of the hot uploader my webpack provided me (which opened things on Microsoft Edge) and it worked... So it was right all this time...!

But for future reference, it seems you can mix certain parts of ES5 and ES6 (at least with the generator-react-webpack)

**Comment by umfana** [comment]
Ok, good to know
