### ISSUE TITLE
Can I fetch a image and save in Parse?

### ISSUE THREAD

**Issue by andyyou** [ParsePlatform/ParseReact#134]
I have tried use Parse in a Swift project and save picture in Parse like this [example](https://github.com/simplyi/ParseSigninWithFacebookAccountIOS/blob/master/FacebookSignInExampleWithParse/ProtectedPageViewController.swift#L70)

By use react-native is there any way to complete this.

Now I try to use `fetch` but didn't work

```
var imageURL = 'https://graph.facebook.com/'+data.id+'/picture?type=large';
fetch(imageURL)
            .then(function(response) {
              return response.blob();
            })
            .then(function(response) {
              picture = new Parse.File(fid, response);
              ParseReact.Mutation.Set({
                className: '_User',
                objectId: user.id
              }, {
                profilePicture: picture,
              }).dispatch({waitForServer: true});
            })
            .done();
```
![](http://i.imgur.com/dvnItDH.png)

Does anyone have any idea to deal this problem that save an image from url to Parse Core.

**Comment by chrillo** [comment]
I did something along these lines in a browser, so not react native, I don't think canvas is available in your environment. You'd need a way to get the base64 encoded data, the code below could give you an idea. Note I had to use a proxy in this code to get around browser security issues. but I think those should not apply for react native.

	function getImageData(img){
	img.setAttribute('crossOrigin', 'anonymous');
	var canvas = document.createElement('canvas')
		canvas.width = preview ? 360 : img.width
		canvas.height = preview ? 360 : img.height
	var ctx = canvas.getContext('2d')
		ctx.drawImage(img,0,0)
	return canvas.toDataURL("image/jpeg",0.6)
	}

	function uploadBase64(base64, callback){
	var name = "photo.jpg"
	var parseFile = new Parse.File(name, {base64: base64.substring(23)})
	parseFile.save().then(function(){
		if(callback){
			callback(null, parseFile)
		}
	}).fail(function(e){
		if(callback){
			callback(e,null)
		}
	})
	}

	function uploadUrl(url,callback){
	var img = new Image()
	img.src = url
	img.onload = function(){
		var data = getImageData(img, preview)
		uploadBase64(data, callback)
	}
	}

	uploadUrl('https://graph.facebook.com/'+data.id+'/picture?type=large', function(err, res){
		console.log(err,res)
	})

**Comment by andyyou** [comment]
@chrillo  thanks a lot

**Comment by temirbekia** [comment]
@andyyou Hi! Please show me your source code how you upload facebook profile image to parse?

**Comment by andyyou** [comment]
@temirbekia The code is quite long time has no maintain.


```js
var graphAPI = 'https://graph.facebook.com/v2.5/'+data.id+'?fields=name,email,picture.width(200).height(200)&access_token='+data.access_token;
var fid, 
    name, 
    email, 
    avatarUrl

fetch(graphAPI)
  .then((response) => response.json())
  .then((responseData) => {
    fid = responseData.id;
    name = responseData.name;
    email = responseData.email;
    avatarUrl = responseData.picture.data.url;

    ParseReact.Mutation.Set({
      className: '_User',
      objectId: user.id
    }, {
      email: email,
      name: name,
      avatarUrl: avatarUrl,
    }).dispatch({waitForServer: true});
  }).then(() => {
    /* Push Notification */
  })
  .done();
```

**Comment by temirbekia** [comment]
@andyyou Thanks for your answer! But I should save like PFILE in parse and how I can do it?
