### ISSUE TITLE
null is not an object (evaluating subscription.originalQuery)

### ISSUE THREAD

**Issue by davidsims9t** [ParsePlatform/ParseReact#135]
I'm attempting to add a relation to a class but I keep on getting this subscription error. I've successfully added a relation by first using ParseReact.Mutation.Create() and then adding the record, but not when I use a pre-existing record.

Works:

ParseReact.Mutation.Create("Media", {
        source: file
      }).dispatch().then((media) => {
        ParseReact.Mutation.AddRelation(object, "media", {
          className: "Media",
          objectId: media.objectId
        }).dispatch().then((response) => {
          
        }, (error) => {
          console.log(error)
        })
      }, (error) => {
        console.log(error)
      })

Doesn't work:

ParseReact.Mutation.AddRelation(object, "media", this.data.user.id)
.dispatch().then((response) => {
console.log(response)
        }, (error) => {
          console.log(error)
        })

Thanks in advance for the help!

**Comment by kevinzzz007** [comment]
@davidsims9t how did you resolve this?

**Comment by davidsims9t** [comment]
@kevinzzz007 I passed in this.props.rowData.id (which evaluates to {className: "ClassName", objectId: "objectId"}) as the first argument in ParseReact.Mutation.AddRelation() which seemed to resolve the issue. I still get the subscription error occasionally, but I'm unable to isolate the problem exactly. I figure it might just be a bug in ParseReact.

**Comment by kevinzzz007** [comment]
I see, thanks!

On Saturday, October 24, 2015, davidsims9t <notifications@github.com> wrote:

> @kevinzzz007 <https://github.com/kevinzzz007> I passed in
> this.props.rowData.id (which evaluates to {className: "ClassName",
> objectId: "objectId"}) as the first argument in
> ParseReact.Mutation.AddRelation() which seemed to resolve the issue. I
> still get the subscription error occasionally, but I'm unable to isolate
> the problem exactly. I figure it might just be a bug in ParseReact.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/ParseReact/issues/135#issuecomment-150856653>
> .
>


-- 
Kevin Zhao | LinkedIn <http://www.linkedin.com/in/kevinzhaouva> | Personal
Blog <https://medium.com/@kevinzhao> | Github
<https://github.com/kevinzzz007>
(434) 282-5369
Computer Science and Information Technology | University of Virginia 2016
Alpha Kappa Psi Professional Business Fraternity
<http://www.akpsiatuva.org/>
