### ISSUE TITLE
StackTrace after using ParseReact.Mutation.Destroy

### ISSUE THREAD

**Issue by nivoc** [ParsePlatform/ParseReact#14]
![image](https://cloud.githubusercontent.com/assets/212133/7036255/7995575c-dd92-11e4-9f31-2bf404aad1da.png)

The content of the mentioned variable in the trace is a string "DESTORY". And that breaks ```var changed = Object.keys(delta.map);```

(Updated description and headline - first was wrong lead)

**Comment by nivoc** [comment]
Umpf. No my solution is wrong. I will have to dive deeper to find the real cause :-(

**Comment by andrewimm** [comment]
Interesting. I'll take a deeper look at this as soon as I can. We actually are planning on moving to immutable-js, but that's some time down the road.

**Comment by nivoc** [comment]
Found it - But not sure why jet.


The content of the mentioned variable in the trace is a string "DESTORY". And that breaks ```var changed = Object.keys(delta.map);```

**Comment by andrewimm** [comment]
Just sounds like a bug on my part. I'll have a fix out later tonight.

**Comment by nivoc** [comment]
Thanks

**Comment by nivoc** [comment]
Note: It does not happen in my app if the debug-window is open.

**Comment by jsierles** [comment]
Same experience here.

**Comment by andrewimm** [comment]
v0.2.0 is out, this should be resolved.
