### ISSUE TITLE
Show proper usage of `observe()` in example

### ISSUE THREAD

**Issue by ludwigschubert** [ParsePlatform/ParseReact#143]
I just fixed an issue I was stuck on for two hours because I didn't know the `observe()` method has `props, state` as parameters. I was using `this.props` and thus subscribed to outdated data when the component would update.

My suggestion would be to change the example in the readme to show that `observe()` takes `props, state` as parameters and that the observed `Parse.Query` should depend on these rather than on `this.props`.

(Let me know if I'm not making myself clear enough. :-) )

**Comment by andrewimm** [comment]
The Readme example is designed to demonstrate the simplicity of observation, it's not really documentation. If you dig into the actual documentation, I think the examples are pretty clear.

Still, I'll update it in case others are getting caught up in similar issues.

**Comment by ludwigschubert** [comment]
Oh, that's a valid caveat! I just discovered the documentation—I didn't think to click on the *Full API* link, somehow that didn't register as documentation for me.

The desire to keep the examples simple is fully understandable.
