### ISSUE TITLE
`observe` does not update the component if a change is made from Parse interface or another tab?

### ISSUE THREAD

**Issue by hoodwink73** [ParsePlatform/ParseReact#145]
After reading the `Subscription.md` in the doc I understood  the observe method will always be called if the **Query** changes.

It is happening locally (within the same browser tab) but if I add new data from Parse web app interface or another tab of the browser, not all instances of the app is reacting to this new change.

I understand invoking `refreshQueries` would update the component, but shouldn't everything happen automatically once the *Query changes*.

I guess, Firebase does that.

**Comment by andrewimm** [comment]
The Parse API is not designed to do this. It's a pull-based API; what you're asking for is push-based, and would required all devices to maintain a constant connection with Parse. If you require this functionality, you can implement a server to handle this using `afterSave` webhooks, but in nearly all cases where developers are looking for clients to update in "real time," I've found that their use case is either handled well by periodic polling, or is not designed to be stored in a document-based database, which is what Parse provides.

Closing, as this is not related to the Parse+React SDK.
