### ISSUE TITLE
ParseReact.Mutation.Set returns error

### ISSUE THREAD

**Issue by jw84** [ParsePlatform/ParseReact#148]
Trying to run this snippet

```
var Parse = require('parse/react-native')
var ParseReact = require('parse-react/react-native')
```

```
var updateUser = ParseReact.Mutation.Set({
  className: "_User",
  objectId: user.id
  }, {
    email: responseData.email
  })
updateUser.dispatch()
```

Generates this

![image](https://cloud.githubusercontent.com/assets/48764/11653936/a8273016-9d56-11e5-8d3a-ff14255fd2fb.png)

user.id and repsonseData.email are both valid

Any insight?

**Comment by jw84** [comment]
Took me awhile but I finally figured it out...

I was trying to set an _User object with new data but turns out I can't directly call it with just className and ObjectId so I threw in the ParseReact ES6 component, setup an observer function to subscribe to ParseReact.currentUser object. I then used that currentUser object for setting changes and everything works.

Best of luck.

**Comment by joshblour** [comment]
This worked for me too! I was doing 
```
   ParseReact.Mutation.Set(
      {
        className: '_User',
        objectId: this.data.user.id
      }, {
        teamName: name
      }
    ).dispatch();
````
and couldn't figure out why user wasn't updating. 

I changed it to:

```
    ParseReact.Mutation.Set(
      this.data.user, {
        teamName: name
      }
    ).dispatch();
```
and it worked perfectly

**Comment by MM-Psiiirus** [comment]
Am i wrong or is  ParseReact.Mutation no longer available for Parse + React Native ?
