### ISSUE TITLE
Parse React broke?

### ISSUE THREAD

**Issue by mrbrackins** [ParsePlatform/ParseReact#171]
I can't get it to work in React Native, and from the looks of these issues, it looks like everyone's using Parse Vanilla SDK or Redux. So is this officially broken?

**Comment by andrewimm** [comment]
It's not broken, but we highly recommend using Redux instead. As noted on the README, Parse+React is not compatible with the Parse SDK beyond version 1.6.14. We are also actively working on a new lightweight SDK that is optimized for Redux-style systems.

**Comment by davodesign84** [comment]
Hi @andrewimm any news about the Redux optimised SDK?

Cheers,
Davide
