### ISSUE TITLE
Cannot Call currentUser() when using a platform with asynch storage system. 

### ISSUE THREAD

**Issue by mrbrackins** [ParsePlatform/ParseReact#172]
Receiving this error when including ParseReact in React Native. 
![screen shot 2016-03-28 at 1 22 14 pm](https://cloud.githubusercontent.com/assets/12778445/14089158/4ca5af94-f4e8-11e5-8fa9-d53ff425e3b6.png)

I'm just creating the Comment Block component on the ParseReact NPM page: https://www.npmjs.com/package/parse-react

**Comment by andrewimm** [comment]
Can you provide the version of the `parse` module that you have installed?

**Comment by andrewimm** [comment]
Nevermind, I see the Live Query stuff in the stack trace. As I mentioned in the other post, and as it says at the top of the README, Parse+React is only compatible with the Parse SDK up to v1.6.14

**Comment by mrbrackins** [comment]
I actually have that version installed: "parse": "^1.6.14",

**Comment by mrbrackins** [comment]
![screen shot 2016-03-28 at 1 33 36 pm](https://cloud.githubusercontent.com/assets/12778445/14089435/c091a178-f4e9-11e5-9fd4-6306e57e049b.png)

**Comment by andrewimm** [comment]
The lines including `LiveQuery` in your stack trace are code that only exists since version 1.8.0. I'd take a look at the package.json in your `node_modules/parse` folder, or try logging `require('parse').CoreManager.get('VERSION')`

**Comment by mrbrackins** [comment]
ah, gotcha. Thx for bearing w/ me!

**Comment by oyvindvol** [comment]
I am using parse 1.6.14, and still get that error in the simulator.
```
Cannot call currentUser() when using a platform with an async storage system. Call currentUserAsync() instead.
```
