### ISSUE TITLE
Use ParseReact with parse-server?

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/ParseReact#177]
Can parse-react be used well with parse-server? I'm reading conflicting points on this.

**Comment by zh-wowtv** [comment]
+1

**Comment by TonyTangAndroid** [comment]
+1

**Comment by marcusfelix** [comment]
+1

**Comment by Wolke** [comment]
+1

2016-07-09 1:17 GMT+08:00 marcusfelix <notifications@github.com>:

> +1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ParsePlatform/ParseReact/issues/177#issuecomment-231418525>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAILmNbrGdTfn9yCGnPzYHXavK7ytZYTks5qToYVgaJpZM4JEbf0>
> .
>



-- 
[1797.tw] 一起救急 一起救您
1797 世界上第一個群眾借貸信用評價平台。
不知道去那找錢?
不知道那個業者正派經營?
立碼po出你的需求，立刻一群人拜託你跟他借錢。

Founder -- Wolke Lin
wolkesau@gmail.com
+886938831136

**Comment by simonbdev** [comment]
I'm using Parse Server via Heroku with parse-react. What's the conflicting point?

**Comment by greggmojica** [comment]
@simonbdev And no issues?

**Comment by hramos** [comment]
Parse Server is backwards compatible with Parse, I don't see why this would be an issue. ParseReact only supports JavaScript SDK versions up to 1.6.14 so you won't be able to take advantage of Parse Server's Live Queries for example, however.
