### ISSUE TITLE
React for Parse 2.2.*

### ISSUE THREAD

**Issue by ngandrew** [ParsePlatform/ParseReact#183]
Since the ParseReact mixin is only for up to Parse 1.6, is there an alternative to this mixin. Or would you just pull in data with parse's javascript api and treat everything else like a normal react app?

I would appreciate an example of the "best" way to get data from parse server.

**Comment by andrewimm** [comment]
It's still in development and light on extra features outside of data handling, but I've been designing [parse-lite](/andrewimm/parse-lite) for all of my Parse + React projects. There are demos there for integration with Redux and React Native there.
