### ISSUE TITLE
Cannot Gain Access to single Object

### ISSUE THREAD

**Issue by skcalanderson2** [ParsePlatform/ParseReact#19]
When I have a query that results in a single query object. How do I get access to the properties of that object? I have to use map for everything? That seems to be the only way to gain access. Further, I have a row with a pointer and I had to manually create a pointer record to get the query to work properly. So I end up with a single query object but cannot do anything with it except map, which makes no damn sense.
```javascript
   observe: function(props, state) {
    	
        var p = {
         "__type": "Pointer",
         "className": "ports",
         "objectId": this.props.port.objectId
     };
        return {
            ports: (new Parse.Query('ports').equalTo('connected_to_1', p))
        }
    },
	render: function() {
		var port = this.data.ports[0];
		console.log(port);
		
		return (
			<div>
				port
			</div>
		);
	}
});

Object {id: 3.Id, className: "ports", objectId: "NJk27dgg8B", createdAt: Tue Apr 14 2015 20:17:25 GMT-0600 (MDT), updatedAt: Tue Apr 14 2015 20:18:45 GMT-0600 (MDT)…}
```
The console shows the object above but I cannot get to any of the properties. Further, it is not a Parse object. So what is it?

**Comment by skcalanderson2** [comment]
Maybe this is just my misunderstanding of Javascript, React, and Parse. But I got this to work this way:

```Javascript
	render: function() {
		var port = JSON.stringify(this.data.ports[0]);
		console.log(port);
		if (typeof port !== 'undefined'){
			console.log(JSON.parse(port).objectId);
			return (
				<div>
					<SubPort objectId={JSON.parse(port).device.objectId} /> Port {JSON.parse(port).number}
				</div>
			);
		}
		return (
			<div>
				Not Connected
			</div>
		);
	}
```

So I stringify it then parse it back, and I can access the properties. I also had to check if it was defined for the times it the component is called with nothing defined for those fields.

Please enlighten me.

**Comment by skcalanderson2** [comment]
This is not an issue. It is because I needed to check for undefined objects before trying to access properties. I added some if checks for undefined and that took care of it.

**Comment by jenbennings** [comment]
I've just run into the same problem—would you mind sharing an updated snippet to demonstrate how you got around this?

**Comment by jenbennings** [comment]
@skcalanderson2 pretty please!

**Comment by skcalanderson2** [comment]
Sorry, have not logged in for a few days. Here is the code that works.

```
var Port = React.createClass({
    mixins: [ParseReact.Mixin],

    observe: function(props, state) {
    	
        var p = {
         "__type": "Pointer",
         "className": "ports",
         "objectId": this.props.port.objectId
     	};
     	if(this.props.number === 1){
        	return {
            	ports: (new Parse.Query('ports').equalTo('connected_to_1', p))
	     	}
	     }else{
	     	return {
            	ports: (new Parse.Query('ports').equalTo('connected_to_2', p))
	     	}
	     }
    },
	render: function() {
		//var port = JSON.stringify(this.data.ports[0]);
		var port = this.data.ports[0];
		if (typeof port !== 'undefined'){
			return (
				<div>
					<SubPort allDevices={this.props.allDevices} objectId={port.device.objectId} /> Port {port.number}
				</div>
			);
		}
		return (
			<div>
				Not Connected
			</div>
		);
	}
});
```
