### ISSUE TITLE
Relational Queries in observe()

### ISSUE THREAD

**Issue by agnosticdev** [ParsePlatform/ParseReact#20]
I am trying to observe the result of a relational Parse query but it looks like the observe() function returns before the Parse query has a chance to return the results needed to populate the observe function.  

Here is an example of my observe function:
```
observe: function() {
  var self = this;

  return {
        parse_data: (self._load_parse_data())
  };
},

_load_parse_data: function(){
  // long relational parse query here
}

```

Is there a better way to do this?

**Comment by agnosticdev** [comment]
I was waiting until the success function was fired.  I returned the result of the query right away and I am getting data.

**Comment by paramaggarwal** [comment]
I didn't understand this completely, anyways this could be documented? I would like to fetch objects with their relations resolved.

**Comment by paramaggarwal** [comment]
Wow, thank you so much @agnosticdev!
