### ISSUE TITLE
Querying for objects equalTo current user doesn't respond to mutations.

### ISSUE THREAD

**Issue by tomdanvers** [ParsePlatform/ParseReact#24]
Apologies in advance if I'm misunderstanding something fundamental about ParseReact but I'm having an issue regarding creating objects associated with the current parse user.

I have a component with the following observe method:
```observe: function() {
            return {
                places: (new Parse.Query('Place'))
                            .equalTo('user', Parse.User.current())
                            .descending('createdAt')
            };
}```

However when I create a new 'Place' object:

```ParseReact.Mutation.Create('Place', {
                    name: 'New Place',
                    user: Parse.User.current()
                }).dispatch();```

...the component doesn't re-render as expected.


Related StackOverflow issue: http://stackoverflow.com/questions/29800798/parse-react-observe-objects-created-by-parse-user-current

**Comment by jsierles** [comment]
If user is a relation field, this may be related to having to call refreshQueries() on the component as described here:

https://github.com/ParsePlatform/ParseReact/blob/master/docs/api/Mutation.md#relation-field-mutations

**Comment by tomdanvers** [comment]
@jsierles that was absolutely the problem! Thanks very much for taking the time to point me in the right direction. When the promise returned by .dispatch() resolves then I call refreshQueries() and all is good! Thanks very much for your help.

                ParseReact.Mutation.Create('Place', {
                    name: 'New Place',
                    user: Parse.User.current()
                })
                .dispatch()
                .then(function() {
                    this.refreshQueries();
                }.bind(this));

p.s. @agnosticdev here is the solution...

**Comment by agnosticdev** [comment]
Excellent, thank you very much!
