### ISSUE TITLE
Looking for Best Practice

### ISSUE THREAD

**Issue by aaronksaunders** [ParsePlatform/ParseReact#29]
I am structuring a common pattern of master detail where I query for the list items and then in a separate modal I allow you to add new items to the list.

When I dispatch the creation of the object in one react component, 

``` javascript
var promise = ParseReact.Mutation.Create('TutorSession', {
    note: 'Parse <3 React',
    place: self.state.selectedPlace.id,
    tutor: self.state.selectedUser.id,
    suggestedDate: self.state.selectedDate,
    user: Parse.User.current()
}).dispatch();

// handle promise results
promise.then(function(obj) {
    // the object was saved successfully.
    console.log(obj);
    self.props.navigator.pop();
}, function(error) {
    // the save failed.
    alert("ERROR\n" + JSON.stringify(error));
});
```
how do I get the the List component to update? Do I need to re-run the query in the List component? This is what I am currently doing.
``` javascript
    observe: function () {
        return {
            tutorSessions: (new Parse.Query("TutorSession").include(["place,tutor,user"]))
        };
    },
```

I noticed that the query was not re-run when i reloaded the component

**Comment by umfana** [comment]
This is a mostly uneducated guess, as I'm also just starting out on React, but how about you shift the mutation/creation to the parent List component? Then hand an `onCreate` handler in to the modal as a prop?

That would be in line with the tutorial here http://facebook.github.io/react/blog/2013/11/05/thinking-in-react.html#step-4-identify-where-your-state-should-live

And you could optimistically add the newly created item to the list if the promise resolves successfully.

**Comment by aaronksaunders** [comment]
Thanks for the reference; I think the take-away here for me is this statement **Since components should only update their own state**
