### ISSUE TITLE
Looking for Best Practice with ActivityIndicatorIOS

### ISSUE THREAD

**Issue by aaronksaunders** [ParsePlatform/ParseReact#30]
I can see how to display the `ActivityIndicatorIOS` when using`this.pendingQueries()` but how is it recommended to show this when using `dispatch` when mutating an object?

**Comment by andrewimm** [comment]
When you dispatch a mutation, it returns a `Parse.Promise` that you can use to add completion / error callbacks.
I'd recommend setting a state variable when you dispatch, and resetting it when the dispatch is completed. Use it to show the ActivityIndicatorIOS.

Something like this:
```
// Somewhere, we dispatch a Mutation
myMutation.dispatch().always(() => {
  // Always set the isMutating state back to false, regardless of success or failure
  this.setState({ isMutating: false });
});
this.setState({ isMutating: true });

// ...

render() {
  return this.state.isMutating ? <ActivityIndicatorIOS /> : null;
}
```

**Comment by aaronksaunders** [comment]
Thanks, makes sense and will give this a go!
