### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by wuichen** [ParsePlatform/ParseReact#33]
can someone help me on setting parse up with react native?

var Parse = require('parse').Parse;

this is the only line that i have and it gives me the error image below

![screen shot 2015-04-30 at 9 14 11 am](https://cloud.githubusercontent.com/assets/6353587/7417203/5ab7e64a-ef19-11e4-827c-2b6058e24e68.png)

It shows that it needs xmlhttprequest module. So I added it.
However, when I added it, it shows another module issues saying that theres a unknown module "url" required.

![screen shot 2015-04-30 at 9 18 28 am](https://cloud.githubusercontent.com/assets/6353587/7417279/e57acb76-ef19-11e4-91e7-f075eb682453.png)

**Comment by wuichen** [comment]
should have required React before Parse

**Comment by andrewimm** [comment]
That's odd. There's no explicit dependency on React from Parse.
How did you install the `parse` package, and what version was it?

**Comment by wuichen** [comment]
I have solved the problem. I installed the lastest parse with npm. The reason thats causing this is probably cause I required parse before react which makes it not being able to find the xmlhttprequest module.

**Comment by athensholloway** [comment]
Just experienced the same issue. requiring react-native before parse resolved it for me as well.
