### ISSUE TITLE
Changes to .include() in version 0.2.1

### ISSUE THREAD

**Issue by ostrgard** [ParsePlatform/ParseReact#36]
Hi!

We have an object from class "List". This object has a pointer to a user. You can change the user but we keep the initial user for logging purpose. So we end up with a Parse Object with two fields: "user" and "initial". If we query this object and .include('user'), both these fields returns with the nested objects. BUT if "user" and "initial" points to the same object, "initial" returns the nested object and "user" returns the pointer object. Same thing happens if we include "initial" instead of "user".

This did not happen in 0.2.0. This is our observe method:
```
observe: function() {
    return {
        list: (new Parse.Query('List')).include('user')
    };
}
```
In the [release notes for version 0.2.1](https://github.com/ParsePlatform/ParseReact/releases/tag/v0.2.1)  the seconds bullet states: 
> When subscribing to queries that use the include() method to fetch nested objects, those nested layers will now be indexed in the ObjectStore

What exactly does this mean, and is this related to the issue we're having?

**Comment by palamccc** [comment]
I'm facing same issue, i have object "Chat", with field "users" (array of pointers of _user collection), when i tried to query 

    (new Parse.Query('Chat')).include('users')

I'm getting following error and stack trace

    Uncaught Error: Cannot store an object without an Id
    storeObject @ ObjectStore.js:58
    storeQueryResults @ ObjectStore.js:296
    _createClass.value.originalQuery.find.then._this.pending @ Subscription.js:145

Its crashing at following method, method expects object, but gets array of objects.

    function storeObject(data) {
      if (!(data.id instanceof Id)) {
        throw new Error('Cannot store an object without an Id');
      }
    ......
    }

**Comment by andrewimm** [comment]
The first issue should have been resolved, but I'm not yet sure what's causing the second issue.

**Comment by ostrgard** [comment]
Hi Andrew! In which release? I used the latest, 0.2.4, when encountering this error.

**Comment by andrewimm** [comment]
@ostrgard sorry, we've fallen behind on uploading releases to our CDN and GitHub releases, since most people were using npm to download everything. I'll get those other sources up to date (we're up to 0.4.1 now!)

**Comment by andrewimm** [comment]
0.4.2 is up on www.parsecdn.com and the releases page of this repo

**Comment by ostrgard** [comment]
Hah, that explains a lot. I'll check it out as soon as possible. You can close this issue :)
