### ISSUE TITLE
Requiring unknown module "parse".

### ISSUE THREAD

**Issue by amccloud** [ParsePlatform/ParseReact#40]
```javascript
var Parse = require('parse');
console.log(Parse);
```

Requiring unknown module "parse". If you are sure the module is there, try restarting the packager."

#### Environment

- Parse 1.4.2
- ReactNative 0.4.0
- Webpack 1.8.10

#### packages.json
```json
{
  "private": true,
  "name": "Nom",
  "version": "0.0.1",
  "scripts": {
    "start": "./node_modules/.bin/react-native-webpack-server start --port 3000 --packagerPort 3001 --webpackPort 3002"
  },
  "dependencies": {
    "babel-core": "^5.1.13",
    "babel-loader": "^5.0.0",
    "immstruct": "git+https://github.com/omniscientjs/immstruct.git",
    "parse": "^1.4.2",
    "react": "^0.13.2",
    "react-hot-loader": "^1.2.5",
    "react-native": "^0.4.0",
    "react-native-camera": "^0.2.0",
    "react-native-facebook-login": "^0.4.5",
    "react-native-webpack-server": "git+https://github.com/mjohnston/react-native-webpack-server.git",
    "uuid": "^2.0.1",
    "webpack": "^1.8.10",
    "webpack-dev-server": "^1.8.2"
  }
}
```

Other modules I have installed work just fine.

**Comment by amccloud** [comment]
Looks like the issue is with babel - specifically because it enables 'use-strict'.

Fix for now was to have webpack exclude parse-latest.js

**Comment by andrewimm** [comment]
Closing because this is an issue with the Parse JS SDK, not with Parse+React. I'll keep this in mind with the next release of the JS SDK, and try to address it then.

If you have more details, they would be helpful. I've compiled applications with the JS SDK and Babel before, and not had an issue.

**Comment by amccloud** [comment]
@andrewimm This is a minimum project that reproduces the issue. https://cl.ly/111P3V3M273x

- npm install
- ./node_modules/webpack-dev-server/bin/webpack-dev-server.js
- Open http://localhost:8080
- Everything works
- Remove the strict blacklist in the webpack config file `&blacklist=strict`
- Restart dev server
- Open http://localhost:8080
- Error in console `Uncaught TypeError: Cannot read property 'Parse' of undefined`

**Comment by andrewimm** [comment]
Thanks, so it's definitely `use strict` causing the issue.
For better or for worse, the Parse SDK uses a hacky `eval()` call to load some React Native-specific modules. Webpack and Browserify ignore it, while the RN packager follows it. It was the only way I could devise to get the SDK to work out of the box with all 3 packagers and no configuration changes.
I've discussed it with the RN team in the past, and we're investigating a decent long-term solution for declaring RN-only modules.
