### ISSUE TITLE
Support Get Query

### ISSUE THREAD

**Issue by jpgilchrist** [ParsePlatform/ParseReact#43]
In cases where I need a single object back, I would like to setup an observe on a get query. For example,

    var GameScore = Parse.Object.extend("GameScore");
    var query = new Parse.Query(GameScore);
    query.get("xWMyZ4YEGZ", {
        success: function(gameScore) {
            // The object was retrieved successfully.
        },
        error: function(object, error) {
            // The object was not retrieved successfully.
            // error is a Parse.Error with an error code and message.
        }
    });

https://parse.com/docs/js/guide#objects-retrieving-objects

I see there's a semi-similar ticket #39 for supporting count queries.

**Comment by agnosticdev** [comment]
Would something like this work for you?

```js
observe: function(props, state) {
  var GameScore = Parse.Object.extend("GameScore");
  var query = new Parse.Query(GameScore);
  query.equalTo("objectId", "xWMyZ4YEGZ");
  query.first();
  
  return {
     gameData: query
  }
}
```

**Comment by jpgilchrist** [comment]
Perhaps what's the difference between using first and get?

**Comment by agnosticdev** [comment]
The only difference as of right now is that I can verify that first works in an observation.

**Comment by mikemintz** [comment]
I think you need ```.limit(1)``` instead of ```.first()```

**Comment by jpgilchrist** [comment]
Most importantly I'd like something to return an object as opposed to an array of results.

**Comment by mikemintz** [comment]
@jpgilchrist no, ```.limit(1)``` will just make sure the array only contains 0 or 1 elements, saving query time and bandwidth. You'll need to do something like this in your render function:

    render() {
      var gameDatum = this.data.gameData[0];
      // gameDatum is now either a parsereact object or undefined, similar to .get()
    }

So this feature would still be useful, to avoid the boilerplate of ```.limit(1)``` and ```this.data.foo[0]```

**Comment by jpgilchrist** [comment]
Right. That's basically what I'm doing, but if I'm always going to be doing that I should just be using the get query, which was the purpose of this issue/ticket. The get query should be supported.

**Comment by TristanBBQ** [comment]
@jpgilchrist did you get a way around this since then?

**Comment by jpgilchrist** [comment]
Yes. I'm using th workaround stated above.

**Comment by jackphel** [comment]
If I'm using the query result in callbacks, this boiler plate
```js
if (this.data.gotten && this.data.gotten.length > 0) {
   return this.data.gotten[0];
}
```
from 
```js
query.equalTo('objectId', 1243)
query.limit(1)
```
ends up all over the place. Do you know how to make the `data.gottenThing` be one object rather than an array of the single object?

**Comment by andrewimm** [comment]
@philikon implemented this in `0.4`, I'll write up some Docs for it later today.

```js
observe() {
  return {
    singleObject: new Parse.Query('Obj').observeOne('someObjectId')
  };
}
```

**Comment by TylerBrock** [comment]
@andrewimm did any documentation ever get created for this?

**Comment by oliviercardoen** [comment]
@andrewimm Thanks for the tip!

**Comment by oliviercardoen** [comment]
@andrewimm this.data.singleObject appears to be 'undefined' at first, which seems obvious. Is there a best practice recommended to write the render method? Or I just write it like following?

```
    render: function() {
        return (
            <div className='project__name'>
                {this.data. singleObject ? this.data. singleObject.name : ''}
            </div>
        );
    }
```

In any cases, thanks for the great library!
