### ISSUE TITLE
ES6 Class support?

### ISSUE THREAD

**Issue by BonerChick** [ParsePlatform/ParseReact#44]
Hi, I'm working on a project that is based on React and Parse, and gladly to find this project. But, when I migrated to es6 class using babel, the [ParseReact.Mixin] seemed not working. I wonder if there is any workaround ? Thanks in advance

**Comment by enu-kuro** [comment]
I tried ParseReact with es6 class and it works.
['react-mixin'](https://github.com/brigand/react-mixin) helps you to use mixin in es6.
[Sample code here](https://gist.github.com/enu-kuro/f7f67cad59d64933b1d6)
Note : Use latest version of 'react-mixin' and 'parse-react'.

**Comment by BonerChick** [comment]
Yes, it works. My problem is using it with mixin. Now you make my day! Thanks!!

**Comment by andrewimm** [comment]
ES6 classes are available in 0.3.0+, take a look at [/docs/api/ES6](/ParsePlatform/ParseReact/blob/master/docs/api/ES6.md)
