### ISSUE TITLE
React-native and Anonymous Users

### ISSUE THREAD

**Issue by ecesena** [ParsePlatform/ParseReact#48]
Will anonymous users be supported in native?
https://www.parse.com/docs/ios/guide#users-anonymous-users

Or, more generally speaking, is there a plan to somehow bind parse for iOS to react-native?

**Comment by andrewimm** [comment]
There are no plans to bind Parse for iOS and React Native -- instead, we're taking the path of making the JS SDK work flawlessly in RN. If we enable anonymous users, it'll be as part of the development cycle of the JS SDK.
