### ISSUE TITLE
AnyBudget app is not working

### ISSUE THREAD

**Issue by bit2pixel** [ParsePlatform/ParseReact#5]
parse-react.js +227 (and a couple of other places) -> uses Parse.Storage.async which I couldn't find in the documentation. Is this like an old parse implementation?

Javascript complains that this doesn't exist.

**Comment by andrewimm** [comment]
Parse+React requires the latest version of our JS SDK - v1.4.0. You can get it at https://parse.com/downloads

**Comment by sebmak** [comment]
When will npm be updated with 1.4.0?

**Comment by andrewimm** [comment]
Odd, I thought I had already published that. Well, it's out now.
