### ISSUE TITLE
How to know the status of observe query result?

### ISSUE THREAD

**Issue by kidwm** [ParsePlatform/ParseReact#54]
I've noticed that the value of `this.data.comments` in render(), it comes first `undefined` then changed to `[]`, and finally get the all results `[...]`, is there any way to separate between *no results* and *query not finished* these two conditions?

Or should it always return `undefined` before query finished?

**Comment by mikemintz** [comment]
Are you sure ```this.data.comments``` is ever undefined in ```render()```? I always have an array in ```render()```, unless I am missing the ```comments``` key from the result of ```observe()```. Could you paste the relevant code?

If you want to differentiate between *no results* and *query not finished*, use ```var loading = this.pendingQueries().indexOf('comments') < 0```

https://github.com/ParsePlatform/ParseReact/blob/master/docs/api/Mixin.md#pendingqueries

**Comment by agnosticdev** [comment]
Yes, like @mikemintz said, try using ```pendingQueries()``` to detect when your data has loaded.  Try something along the line of this:

```js
observe: function() {
 return {
   comments: query
 }
},
render: function() {
 var returnData;
 if (this.pendingQueries().length > 0) {
  returnData = (<div className="loading"></div>);
 } else {
  returnData = this.data.comments.map(function(obj) {
      return (
        <div key={obj.objectId}>
          <p>{obj.text}</p>
        </div>
      );
    });
 }
 return (<div>{returnData}</div>);
}
```

**Comment by kidwm** [comment]
Thanks guys!
@mikemintz You're right, that's because my query changed after user logged-in:
```js
observe: function(props) {
		var user = Parse.User.current();
		return user ? {
			items: user.relation('favorites').query()
		} : null;
	},
```
@agnosticdev Thanks for your kindly offered snippet.

**Comment by kevinzzz007** [comment]
@agnosticdev thank you so much!  Spent hours on trying to find a way to do this and this solved everything :-) :+1:

**Comment by agnosticdev** [comment]
@kevinzzz007 no problem!  Glad I could help out.
