### ISSUE TITLE
Error during query in ObjectStore.deepFetch if any field is null

### ISSUE THREAD

**Issue by mikemintz** [ParsePlatform/ParseReact#56]
If I perform a query and any field of any retrieved object is null, ParseReact has this error in ObjectStore.deepFetch on the 3rd line of this excerpt

```Uncaught TypeError: Cannot read property '__type' of null```

    for (var attr in source) {
      var sourceVal = source[attr];
      if (typeof sourceVal === 'object' && sourceVal.__type === 'Pointer') {
        var childId = new Id(sourceVal.className, sourceVal.objectId);
        if (seen.indexOf(childId.toString()) < 0 && store[childId]) {

https://github.com/ParsePlatform/ParseReact/blob/master/src/ObjectStore.js#L370

I can work around this for now by making sure my parse database never has any null fields. Would it make sense to fix it by adding an extra guard condition like ```sourceVal !== null```?

**Comment by mikemintz** [comment]
Oh I see this is addressed in an open PR already: https://github.com/ParsePlatform/ParseReact/pull/42

**Comment by rohit-romley** [comment]
Did you find any solution for this?
