### ISSUE TITLE
Uncaught Error: Object is attached to a nonexistant subscription when ParseReact.Mutation.Destroy(item).dispatch()

### ISSUE THREAD

**Issue by kidwm** [ParsePlatform/ParseReact#59]
```js
observe: function(props, state) {
	return {
		item: (new Parse.Query('Item')).equalTo('objectId', this.context.router.getCurrentParams().itemId)
	};
},
```

when i do `ParseReact.Mutation.Destroy(this.data.item[0]).dispatch()` I will get this error:
*Uncaught Error: Object is attached to a nonexistant subscription*
What's wrong?

P.S. typo in source: `nonexistant`  should be `nonexistent`

**Comment by andrewimm** [comment]
I'm trying to track down this issue, but I'm having trouble replicating the bug with the code above. Is there a minimal case you can generate that reliably causes this exception to be thrown?

**Comment by andrewimm** [comment]
I think I found the answer: when a subscription was disposed, objects in its result set did not clean up their references to it. When they were updated, they attempted to inform this subscription, which now did not exist. I'm about to push v0.3.1, which includes a fix for this. If it's no longer an issue, we can close this out.

**Comment by kidwm** [comment]
@andrewimm Thanks, it works in 0.3.1
