### ISSUE TITLE
react-native compatability

### ISSUE THREAD

**Issue by magus** [ParsePlatform/ParseReact#9]
Assuming this is a use case that we would want to support in the future, it seems to not be working as expected in my root react-native app component.
```jsx
var React = require('react-native');
var Parse = require('parse').Parse;
var ParseReact = require('parse-react');

// Make react and parse global
window.React = React;
window.Parse = Parse;
window.ParseReact = ParseReact;
```

throws...
![screen shot 2015-03-29 at 9 57 52 pm](https://cloud.githubusercontent.com/assets/290084/6890381/bd28f5cc-d65e-11e4-9aa4-e977add80587.png)

**Comment by magus** [comment]
This might be due to some loading race, moving the statement after another require seems to delay it enough for the React == 'undefined' to return false and continue in ParseReact.js. It then fails when requiring LocalSubscriptions due to 'process' not existing. Testing `process.env.NODE_ENV` occurs in multiple locations (warning.js, ObjectStore.js, etc.) so it might need slight refactoring to be compatible with react-native but possible.

**Comment by magus** [comment]
Since `var React = window.React = require('React')` doesn't work in react-native, didn't dig to find out why, I refactored to the snippet in the initial issue comment. So obviously, I had to move the ParseReact require to after the `window.React = React` statement. Doing so resolves the issue making React a global so it can be accessed later inside ParseReact.js.

Assuming the `process.env.NODE_ENV` is polyfilled or replaced with something like `__DEV__` (the react-native global which designates the packagers returned js bundle type) when process isn't available, the library should be compatible. I've gone through and made the changes locally to confirm it imports correctly after replacing the `process.env.NODE_ENV == 'test'` with `true`

**Comment by nirmalpatel** [comment]
How did you solve "Can't find variable: process" error?

**Comment by magus** [comment]
>replacing the `process.env.NODE_ENV == 'test'` with `true`

**Comment by andrewimm** [comment]
Just pushed v0.1.3 to npm. This should fix all of the weird React Native-related bugs, including the `process` issue. You now no longer have to do anything hacky to explicitly add Parse or React to the global scope.
