### ISSUE TITLE
ParseReact and Flux

### ISSUE THREAD

**Issue by jasecoop** [ParsePlatform/ParseReact#94]
Hi — firstly, ParseReact has been great. Thanks!

My app is getting to a point where I need to rethink it's structure and I've been looking to implement Flux.

I was wondering how ParseReact's observe and mutate methods play with Flux. Is there a need for Flux? Or is it simply a matter of observing and mutating where appropriate in the Flux store.

If anyone has any opinions on this, or even better, some examples. I'd love to hear more.

Cheers

Jase

**Comment by TylerBrock** [comment]
As would I. Great question. I see it somewhat as an implementation of Flux in that objects that are being observed are notified on mutations. Would love to hear from @andrewimm on this though.

**Comment by steve0hh** [comment]
>It's using a Flux-type store behind the scenes. Because we control the data types, we were able to generalize the store, and create one in the background that manages all of the behaviors we need. This way, app developers can avoid the typical boilerplate (like instantiating a Store) that often accompanies Flux development.
    I like to refer to this library as "Opinionated Flux." We took the good parts, removed some abstractions we didn't need, and hid as much as we could. We worked closely with the Flux teams within FB when we made these decisions, and we're exploring more adventurous takes (such as pure-functional stores) as we move forward.

> -- @andrewimm taken from this [comment](http://blog.parse.com/learn/parse-and-react-shared-chemistry/#comment-2072724177)

**Comment by andrewimm** [comment]
I responded on Twitter: https://twitter.com/immediatedelay/status/621038723333931008
