### ISSUE TITLE
ParseReact.Mutation.Batch - Remove Duplicates

### ISSUE THREAD

**Issue by tomdanvers** [ParsePlatform/ParseReact#96]
Hi,
Thanks for the amazing work on ParseReact!

I have a question that could be an issue (or perhaps I'm just missing a trick somewhere!).

I'm using parse react to update a parse object which is a long string. I use a textarea element and onChange I add the new value to a ParseReact.Mutation.Batch instance using ParseReact.Mutation.Set (and dispatching it with the batch option). When the text area loses focus I dispatch the batch. At this point the batch contains multiple 'set' mutations on the same property of the same Parse object. When the batch is dispatched all the versions of the mutation of the same property get applied to the parse object and the latest one isn't always the one that actually gets stored in Parse. What am I doing wrong!?

Thanks in advance.

**Comment by tomdanvers** [comment]
I did some more reading of the React docs and realised I was implementing the component incorrectly.

**Comment by kevinzzz007** [comment]
@tomdanvers could you share how you solved the issue?  thanks!
