### ISSUE TITLE
[feature request] Set ACLs on created objects

### ISSUE THREAD

**Issue by jaredly** [ParsePlatform/ParseReact#98]
It doesn't look like it's possible at the moment to set the ACL on a `Mutation.Create`'d object. Is this planned?

**Comment by andrewimm** [comment]
@jaredly take a look at the source for the AnyBudget example, it uses ACLs to restrict data visibility.
Is there something more specific you'd like API-wise?

**Comment by jaredly** [comment]
oh awesome! I didn't realize you could just set `ACL` like that. [The docs](https://www.parse.com/docs/js/guide#security) made it look like you need to `.setACL()` on the record object.
Thanks!
